In [1]:
import torch

In [6]:
a = torch.FloatTensor([[1,2],
                       [3,4]])
b = torch.FloatTensor([[2,2],
                       [3,3]])

In [7]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [8]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [9]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [10]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [11]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

In [12]:
a == b

tensor([[False,  True],
        [ True, False]])

In [13]:
a != b

tensor([[ True, False],
        [False,  True]])

In [14]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [15]:
print(a.mul(b))

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [16]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [17]:
print(a.mul_(b))

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [18]:
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [19]:
x = torch.FloatTensor([[1,2],
                       [3,4]])

In [20]:
print(x.sum())

tensor(10.)


In [21]:
print(x.mean())

tensor(2.5000)


In [22]:
print(x.sum(dim=0))

tensor([4., 6.])


In [23]:
print(x.sum(dim=-1))

tensor([3., 7.])


In [25]:
y = 1

In [26]:
z = x + y
print(z)

tensor([[2., 3.],
        [4., 5.]])


In [27]:
print(z.size())

torch.Size([2, 2])


In [28]:
x = torch.FloatTensor([[1,2],
                       [4,8]])
y = torch.FloatTensor([3,5])

In [29]:
print(x.size())

torch.Size([2, 2])


In [30]:
print(y.size())

torch.Size([2])


In [31]:
z = x + y
print(z)

tensor([[ 4.,  7.],
        [ 7., 13.]])


In [32]:
x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([3,5])

In [33]:
print(x.size())

torch.Size([1, 1, 2])


In [34]:
print(y.size())

torch.Size([2])


In [35]:
z = x + y

In [36]:
print(z)

tensor([[[4., 7.]]])


In [37]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[3], [5]])

In [39]:
print(x.size())

torch.Size([1, 2])


In [40]:
print(y.size())

torch.Size([2, 1])


In [41]:
z = x + y
print(z)

tensor([[4., 5.],
        [6., 7.]])


In [42]:
print(z.size())

torch.Size([2, 2])


In [45]:
x = torch.FloatTensor([[[1, 2],
                       [3,4]],
                       [[5,6],
                       [7,8]],
                       [[9,10],
                       [11,12]]])

In [46]:
print(x.size())

torch.Size([3, 2, 2])


In [47]:
print(x.view(12))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [48]:
print(x.view(3,4))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [49]:
print(x.view(3,1,4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [50]:
print(x.view(-1))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [51]:
print(x.view(3, -1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [53]:
print(x.view(-1, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [54]:
y = x.view(3, 4)

In [56]:
x.storage().data_ptr() == y.storage().data_ptr()

True

In [57]:
print(x.reshape(3, 4))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [60]:
x = torch.FloatTensor([[[1,2],
                        [3, 4]]])
print(x.size())

torch.Size([1, 2, 2])


In [61]:
print(x.squeeze())

tensor([[1., 2.],
        [3., 4.]])


In [62]:
print(x.squeeze().size())

torch.Size([2, 2])


In [63]:
print(x.squeeze(0).size())

torch.Size([2, 2])


In [64]:
print(x.squeeze(1).size())

torch.Size([1, 2, 2])


In [65]:
x = torch.FloatTensor([[1,2], [3,4]])
print(x.size())

torch.Size([2, 2])


In [67]:
print(x.unsqueeze(1).size())

torch.Size([2, 1, 2])


In [68]:
print(x.unsqueeze(-1).size())

torch.Size([2, 2, 1])


In [69]:
print(x.unsqueeze(2).size())

torch.Size([2, 2, 1])


In [72]:
print(x.reshape(2, 2, -1).size())

torch.Size([2, 2, 1])


In [74]:
x = torch.FloatTensor([[[1, 2],
                       [3,4]],
                       [[5,6],
                       [7,8]],
                       [[9,10],
                       [11,12]]])

In [75]:
print(x.size())

torch.Size([3, 2, 2])


In [76]:
print(x[0])

tensor([[1., 2.],
        [3., 4.]])


In [77]:
print(x[-1])

tensor([[ 9., 10.],
        [11., 12.]])


In [78]:
print(x[:, 0])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [79]:
print(x[1:2, 1:, :].size())

torch.Size([1, 1, 2])


In [83]:
x = torch.FloatTensor(10, 4)

splits = x.split(4, dim = 0)
for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [85]:
x = torch.FloatTensor(8, 4)

In [86]:
chunks = x.chunk(3, dim = 0)
for c in chunks:
    print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


In [88]:
x = torch.FloatTensor([[[1,1],
                        [2,2]],
                       [[3,3],
                        [4,4]],
                       [[5,5],
                        [6,6]]])
indice = torch.LongTensor([2, 1])
print(x.size())

torch.Size([3, 2, 2])


In [90]:
y = x.index_select(dim=0, index = indice)
print(y)

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])


In [91]:
print(y.size())

torch.Size([2, 2, 2])


In [92]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
y = torch.FloatTensor([[10,11,12],
                       [13,14,15],
                       [16,17,18]])

print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [93]:
z = torch.cat([x, y], dim = 0)
print(z)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])


In [94]:
print(z.size())

torch.Size([6, 3])


In [95]:
z = torch.cat([x, y], dim = 1)
print(z)

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])


In [96]:
print(z.size())

torch.Size([3, 6])


In [97]:
z = torch.stack([x, y])
print(z)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])


In [98]:
print(z.size())

torch.Size([2, 3, 3])


In [99]:
z = torch.stack([x, y], dim = -1)
print(z)

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])


In [101]:
z.size()

torch.Size([3, 3, 2])

In [103]:
d = 0
z = torch.cat([x.unsqueeze(d), y.unsqueeze(d)], dim = d)
print(z)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])


In [104]:
print(z.size())

torch.Size([2, 3, 3])


In [105]:
result = []

for i in range(5):
    x = torch.FloatTensor(2,2)
    result += [x]
result = torch.stack(result)

print(result)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [107]:
x = torch.FloatTensor([[[1,2]],
                        [[3,4]]])
print(x.size())

torch.Size([2, 1, 2])


In [108]:
y = x.expand(2,3,2)
print(y)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


In [109]:
print(y.size())

torch.Size([2, 3, 2])


In [111]:
y = torch.cat([x]*3,dim = 1)
y

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])

In [113]:
x = torch.randperm(10)
print(x)

tensor([1, 0, 6, 3, 8, 9, 5, 2, 7, 4])


In [114]:
x = torch.randperm(3**3).reshape(3, 3, -1)

In [115]:
print(x)

tensor([[[ 5, 26,  9],
         [14, 13,  2],
         [22, 15, 10]],

        [[ 0,  1, 23],
         [24, 20, 21],
         [ 6, 16, 12]],

        [[11, 17,  4],
         [18,  8,  7],
         [19, 25,  3]]])


In [116]:
x.size()

torch.Size([3, 3, 3])

In [117]:
y = x.argmax(dim = -1)
print(y)

tensor([[1, 0, 0],
        [2, 0, 1],
        [1, 0, 1]])


In [127]:
values, indices = torch.topk(x, k = 1, dim = 1)

In [128]:
print(values.size())

torch.Size([3, 1, 3])


In [129]:
values

tensor([[[22, 26, 10]],

        [[24, 20, 23]],

        [[19, 25,  7]]])

In [130]:
print(indices.size())

torch.Size([3, 1, 3])


In [133]:
_, indices = torch.topk(x , k = 2, dim = -1)
print(indices.size())

torch.Size([3, 3, 2])


In [134]:
indices

tensor([[[1, 2],
         [0, 1],
         [0, 1]],

        [[2, 1],
         [0, 2],
         [1, 2]],

        [[1, 0],
         [0, 1],
         [1, 0]]])

In [141]:
values, indices = torch.sort(x ,dim = -1)


In [142]:
values

tensor([[[ 5,  9, 26],
         [ 2, 13, 14],
         [10, 15, 22]],

        [[ 0,  1, 23],
         [20, 21, 24],
         [ 6, 12, 16]],

        [[ 4, 11, 17],
         [ 7,  8, 18],
         [ 3, 19, 25]]])

In [143]:
target_dim = -1
values, indices = torch.topk(x, k = x.size(target_dim), largest = False)
print(values)

tensor([[[ 5,  9, 26],
         [ 2, 13, 14],
         [10, 15, 22]],

        [[ 0,  1, 23],
         [20, 21, 24],
         [ 6, 12, 16]],

        [[ 4, 11, 17],
         [ 7,  8, 18],
         [ 3, 19, 25]]])


In [144]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)
print(x)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


In [145]:
print(x.size())

torch.Size([3, 3])


In [146]:
mask = x > 4
print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [148]:
y = x.masked_fill(mask, value=-1)
print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


In [149]:
print(torch.ones(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [150]:
print(torch.zeros(2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [151]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])

print(x.size())

torch.Size([2, 3])


In [152]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [153]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
