In [17]:
import torch
import torch.nn as nn

In [2]:
x = torch.FloatTensor([[1,2],
                       [3,4],
                       [5,6]])

y = torch.FloatTensor([[1,2],
                       [1,2]])

In [3]:
print(x.size(), y.size())

torch.Size([3, 2]) torch.Size([2, 2])


In [4]:
z = torch.matmul(x, y)
print(z.size())

torch.Size([3, 2])


In [6]:
print(z)

tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])


In [7]:
x = torch.FloatTensor(3,3,2)
y = torch.FloatTensor(3,2,3)

In [9]:
z = torch.bmm(x, y)
print(z)
print(z.size())

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([3, 3, 3])


In [14]:
W = torch.FloatTensor([[1,2],
                       [3,4],
                       [5,6]])
b = torch.FloatTensor([2,2])

In [11]:
def linear(x, W, b):
    y = torch.matmul(x, W) + b

    return y

In [12]:
x = torch.FloatTensor(4,3)

In [15]:
y = linear(x, W, b)

In [16]:
print(y.size())

torch.Size([4, 2])


In [20]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = 3
        self.output_dim = 2

        super().__init__()
        # 학습 불가능
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)
    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b

        return y

In [21]:
linear = MyLinear(3,2)

y = linear(x)
print(y)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [22]:
for p in linear.parameters():
    print(p)

In [23]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = 3
        self.output_dim = 2

        super().__init__()
        # 학습 가능
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b

        return y

In [25]:
linear = MyLinear(3,2)

for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [26]:
linear = nn.Linear(3,2)

y = linear(x)

In [27]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.5060,  0.0921,  0.2821],
        [ 0.0285, -0.3802,  0.0577]], requires_grad=True)
Parameter containing:
tensor([0.3787, 0.4032], requires_grad=True)


In [32]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = 3
        self.output_dim = 2

        super().__init__()
        # 학습 가능
        self.linear = nn.Linear(input_dim, output_dim)
    def forward(self, x):
        y = self.linear(x)

        return y

In [33]:
linear = MyLinear(3,2)
y = linear(x)
print(y)

tensor([[ 0.0374, -0.1273],
        [ 0.0374, -0.1273],
        [ 0.0374, -0.1273],
        [ 0.0374, -0.1273]], grad_fn=<AddmmBackward0>)


In [39]:
x = torch.FloatTensor(2,2).to('mps')
x

tensor([[0., 0.],
        [0., 0.]], device='mps:0')

In [41]:
x = torch.FloatTensor(2,2)
x.to('mps')

tensor([[0., 0.],
        [0., 0.]], device='mps:0')

In [42]:
layer = nn.Linear(2,2)
layer.to('mps')

Linear(in_features=2, out_features=2, bias=True)

In [44]:
x = torch.FloatTensor(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [46]:
x.to('mps')

tensor([[0., 0.],
        [0., 0.]], device='mps:0')

In [50]:
cpu_device = torch.device('cpu')
# gpu_device = torch.device('cuda:0')
# Mac M2
gpu_device = torch.device('mps')

In [54]:
next(layer.parameters()).device

device(type='mps', index=0)