# 경사하강법

In [1]:
import torch
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [3]:
x = torch.rand_like(target)
x.requires_grad = True

In [4]:
loss = F.mse_loss(x, target)
print(loss)

tensor(0.0685, grad_fn=<MseLossBackward0>)


In [5]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    loss.backward(retain_graph=True)

    x = x - learning_rate*x.grad
    x.detach_()
    x.requires_grad_(True)

    loss = F.mse_loss(x, target)
    print('%d-th Loss: %.4e'%(iter_cnt, loss))
    print(x)

1-th Loss: 4.1435e-02
tensor([[0.2518, 0.2564, 0.0783],
        [0.4889, 0.4280, 0.5024],
        [0.2044, 0.8329, 0.7319]], requires_grad=True)
2-th Loss: 2.5065e-02
tensor([[0.2181, 0.2439, 0.1276],
        [0.4691, 0.4440, 0.5241],
        [0.3145, 0.8256, 0.7693]], requires_grad=True)
3-th Loss: 1.5163e-02
tensor([[0.1918, 0.2341, 0.1659],
        [0.4538, 0.4564, 0.5410],
        [0.4002, 0.8199, 0.7983]], requires_grad=True)
4-th Loss: 9.1727e-03
tensor([[0.1714, 0.2265, 0.1957],
        [0.4418, 0.4661, 0.5541],
        [0.4668, 0.8155, 0.8209]], requires_grad=True)
5-th Loss: 5.5489e-03
tensor([[0.1555, 0.2206, 0.2189],
        [0.4325, 0.4736, 0.5643],
        [0.5186, 0.8120, 0.8385]], requires_grad=True)
6-th Loss: 3.3568e-03
tensor([[0.1432, 0.2161, 0.2369],
        [0.4253, 0.4795, 0.5722],
        [0.5589, 0.8094, 0.8522]], requires_grad=True)
7-th Loss: 2.0306e-03
tensor([[0.1336, 0.2125, 0.2509],
        [0.4197, 0.4841, 0.5784],
        [0.5903, 0.8073, 0.8628]], requi

In [6]:
x = torch.FloatTensor([[1,2],
                       [3,4]]).requires_grad_(True)

In [7]:
x1 = x + 2
print(x1)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)


In [9]:
x2 = x - 2
print(x2)

tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)


In [10]:
x3 = x1 * x2
print(x3)

tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)


In [11]:
y = x3.sum()
print(y)

tensor(14., grad_fn=<SumBackward0>)


In [12]:
y.backward()

In [13]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


In [14]:
x

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [15]:
x3.detach_()

tensor([[-3.,  0.],
        [ 5., 12.]])